# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
#  source: firefly.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'firefly.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfirefly.proto\"\x1d\n\x0cPhaseRequest\x12\r\n\x05phase\x18\x01 \x01(\x01\"\x1e\n\rPhaseResponse\x12\r\n\x05phase\x18\x01 \x01(\x01\x32>\n\x0e\x46ireflyService\x12,\n\tSendPhase\x12\r.PhaseRequest\x1a\x0e.PhaseResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firefly_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHASEREQUEST']._serialized_start=17
  _globals['_PHASEREQUEST']._serialized_end=46
  _globals['_PHASERESPONSE']._serialized_start=48
  _globals['_PHASERESPONSE']._serialized_end=78
  _globals['_FIREFLYSERVICE']._serialized_start=80
  _globals['_FIREFLYSERVICE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
